title: Adebajo Adewale Olamilekan

logo: adem.jpg

description: A Data Analyst with experience using Excel for Data analysis, SQL for data manipulation and interogation and PowerBi for creating business intelligent report  .

# show_downloads: true

# google_analytics:

theme: jekyll-theme-minimal
 
